# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:
# trabalhos/tarefas dentro do pipeline = jobs

jobs:
  test:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - name: checkout repositório
        uses: actions/checkout@v3

      # instalação do node
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # instalação do Yarn
      - name: Instalando Yarn
        run:  yarn install

      # Executando testes
      - name: Executar testes
        run: yarn test

   

      
